DROP TABLE PERSON_INFO;

CREATE TABLE PERSON_INFO (
  ID INT  NOT NULL,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  PRIMARY KEY (ID)
);

DROP TABLE S_PERSON_INFO;

CREATE TABLE S_PERSON_INFO (
	ID INT NOT NULL AUTO_INCREMENT,
	UID VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE KEY(UID)
);